name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 🔑 Setup SSH Connection
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/ls-fitnes-api/htdocs/api.ls-fitnes.com
            git reset --hard origin/master    
            git pull origin master

            export NVM_DIR="$HOME/.nvm"
            source $NVM_DIR/nvm.sh  
            export PATH=$PATH:$NVM_DIR/versions/node/v22.13.0/bin 

            echo "🔍 Checking environment..."
            whoami
            which pm2
            node -v
            npm -v
            ls -lah

            echo "🔥 Cleaning old cache..."
            rm -rf node_modules package-lock.json
            npm install 


            echo "🛑 Killing PM2 processes..."
            pm2 kill  
            pm2 flush 

            echo "❌ Deleting old API process..."
            pm2 delete api || true 

            echo "🚀 Starting API..."
            NODE_ENV=production pm2 start server.js --name api

            echo "🛠 Saving PM2 process..."
            pm2 save  

            echo "✅ Deployment completed successfully!"
          EOF
