name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 🔑 Setup SSH Connection
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/ls-fitnes-api/htdocs/api.ls-fitnes.com
            git reset --hard origin/master    
            git pull origin master

            export NVM_DIR="$HOME/.nvm"
            source $NVM_DIR/nvm.sh  
            export PATH=$PATH:$NVM_DIR/versions/node/v22.13.0/bin 
            
            npm install   
            pm2 restart all || pm2 delete api || pm2 start server.js --name api

          EOF
